(* -*- coqchk-prog-args: ("-j" "4") -*- *)

(* rocqchk -j 4 checks the opaque proofs below in worker processes: there
   are enough of them that the first share is worth a fork. *)

Axiom A : Prop.
Axiom a : A.

Lemma l1 : A. Proof. exact a. Qed.
Lemma l2 : A. Proof. exact a. Qed.
Lemma l3 : A. Proof. exact a. Qed.
Lemma l4 : A. Proof. exact a. Qed.
Lemma l5 : A. Proof. exact a. Qed.
Lemma l6 : A. Proof. exact a. Qed.
Lemma l7 : A. Proof. exact a. Qed.
Lemma l8 : A. Proof. exact a. Qed.
Lemma l9 : A. Proof. exact a. Qed.
Lemma l10 : A. Proof. exact a. Qed.
Lemma l11 : A. Proof. exact a. Qed.
Lemma l12 : A. Proof. exact a. Qed.
Lemma l13 : A. Proof. exact a. Qed.
Lemma l14 : A. Proof. exact a. Qed.
Lemma l15 : A. Proof. exact a. Qed.
Lemma l16 : A. Proof. exact a. Qed.
Lemma l17 : A. Proof. exact a. Qed.
Lemma l18 : A. Proof. exact a. Qed.
Lemma l19 : A. Proof. exact a. Qed.
Lemma l20 : A. Proof. exact a. Qed.
Lemma l21 : A. Proof. exact a. Qed.
Lemma l22 : A. Proof. exact a. Qed.
Lemma l23 : A. Proof. exact a. Qed.
Lemma l24 : A. Proof. exact a. Qed.
Lemma l25 : A. Proof. exact a. Qed.
Lemma l26 : A. Proof. exact a. Qed.
Lemma l27 : A. Proof. exact a. Qed.
Lemma l28 : A. Proof. exact a. Qed.
Lemma l29 : A. Proof. exact a. Qed.
Lemma l30 : A. Proof. exact a. Qed.
Lemma l31 : A. Proof. exact a. Qed.
Lemma l32 : A. Proof. exact a. Qed.
Lemma l33 : A. Proof. exact a. Qed.
Lemma l34 : A. Proof. exact a. Qed.
Lemma l35 : A. Proof. exact a. Qed.
Lemma l36 : A. Proof. exact a. Qed.
Lemma l37 : A. Proof. exact a. Qed.
Lemma l38 : A. Proof. exact a. Qed.
Lemma l39 : A. Proof. exact a. Qed.
Lemma l40 : A. Proof. exact a. Qed.
Lemma l41 : A. Proof. exact a. Qed.
Lemma l42 : A. Proof. exact a. Qed.
Lemma l43 : A. Proof. exact a. Qed.
Lemma l44 : A. Proof. exact a. Qed.
Lemma l45 : A. Proof. exact a. Qed.
Lemma l46 : A. Proof. exact a. Qed.
Lemma l47 : A. Proof. exact a. Qed.
Lemma l48 : A. Proof. exact a. Qed.
Lemma l49 : A. Proof. exact a. Qed.
Lemma l50 : A. Proof. exact a. Qed.
Lemma l51 : A. Proof. exact a. Qed.
Lemma l52 : A. Proof. exact a. Qed.
Lemma l53 : A. Proof. exact a. Qed.
Lemma l54 : A. Proof. exact a. Qed.
Lemma l55 : A. Proof. exact a. Qed.
Lemma l56 : A. Proof. exact a. Qed.
Lemma l57 : A. Proof. exact a. Qed.
Lemma l58 : A. Proof. exact a. Qed.
Lemma l59 : A. Proof. exact a. Qed.
Lemma l60 : A. Proof. exact a. Qed.
Lemma l61 : A. Proof. exact a. Qed.
Lemma l62 : A. Proof. exact a. Qed.
Lemma l63 : A. Proof. exact a. Qed.
Lemma l64 : A. Proof. exact a. Qed.
Lemma l65 : A. Proof. exact a. Qed.
Lemma l66 : A. Proof. exact a. Qed.
Lemma l67 : A. Proof. exact a. Qed.
Lemma l68 : A. Proof. exact a. Qed.
Lemma l69 : A. Proof. exact a. Qed.
Lemma l70 : A. Proof. exact a. Qed.
Lemma l71 : A. Proof. exact a. Qed.
Lemma l72 : A. Proof. exact a. Qed.
Lemma l73 : A. Proof. exact a. Qed.
Lemma l74 : A. Proof. exact a. Qed.
Lemma l75 : A. Proof. exact a. Qed.
Lemma l76 : A. Proof. exact a. Qed.
Lemma l77 : A. Proof. exact a. Qed.
Lemma l78 : A. Proof. exact a. Qed.
Lemma l79 : A. Proof. exact a. Qed.
Lemma l80 : A. Proof. exact a. Qed.
Lemma l81 : A. Proof. exact a. Qed.
Lemma l82 : A. Proof. exact a. Qed.
Lemma l83 : A. Proof. exact a. Qed.
Lemma l84 : A. Proof. exact a. Qed.
Lemma l85 : A. Proof. exact a. Qed.
Lemma l86 : A. Proof. exact a. Qed.
Lemma l87 : A. Proof. exact a. Qed.
Lemma l88 : A. Proof. exact a. Qed.
Lemma l89 : A. Proof. exact a. Qed.
Lemma l90 : A. Proof. exact a. Qed.
Lemma l91 : A. Proof. exact a. Qed.
Lemma l92 : A. Proof. exact a. Qed.
Lemma l93 : A. Proof. exact a. Qed.
Lemma l94 : A. Proof. exact a. Qed.
Lemma l95 : A. Proof. exact a. Qed.
Lemma l96 : A. Proof. exact a. Qed.
Lemma l97 : A. Proof. exact a. Qed.
Lemma l98 : A. Proof. exact a. Qed.
Lemma l99 : A. Proof. exact a. Qed.
Lemma l100 : A. Proof. exact a. Qed.
